[workspace]
resolver = "2"
members = [
    "crates/aleph-cli",
    "crates/aleph-sdk",
    "crates/aleph-types",
]

[workspace.dependencies]
aleph-sdk = { path = "crates/aleph-sdk", version = "0.4.0" }
aleph-types = { path = "crates/aleph-types", version = "0.4.0" }
anyhow = { version = "1.0.100" }
assert_matches = { version = "1.5.0" }
chrono = { version = "0.4.42" }
clap = { version = "4.5.51", features = ["derive"] }
futures-util = { version = "0.3" }
reqwest = { version = "0.12.24", features = ["json"] }
rstest = { version = "0.26.1" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145" }
serde_qs = { version = "0.13" }
serde_with = "3.15.1"
sha2 = { version = "0.10.9" }
thiserror = { version = "2.0.17" }
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"]  }
tokio-stream = { version = "0.1" }
tokio-tungstenite = { version = "0.26", features = ["native-tls"] }
url = { version = "2.5.7" }
