[package]
name = "aleph-sdk"
version = "0.4.0"
edition = "2024"
description = "Aleph Cloud SDK for client applications."
license = "MIT"
repository = "https://github.com/aleph-im/aleph-rs"
homepage = "https://github.com/aleph-im/aleph-rs"

[dependencies]
aleph-types = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
serde_with = { workspace = true }
tokio-tungstenite = { workspace = true }
tokio-stream = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }
serde_qs = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
