[package]
name = "aleph-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
aleph-types = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
serde_with = { workspace = true }
