[package]
name = "aleph-cli"
version = "0.1.0-rc1"
edition = "2024"

[dependencies]
aleph-sdk = { workspace = true }
aleph-types = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[[bin]]
name = "aleph"
path = "src/main.rs"
