[package]
name = "aleph-cli"
version = "0.4.0"
edition = "2024"
description = "Minimal CLI for Aleph Cloud, built in Rust."
license = "MIT"
repository = "https://github.com/aleph-im/aleph-rs"
homepage = "https://github.com/aleph-im/aleph-rs"

[dependencies]
aleph-sdk = { workspace = true }
aleph-types = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[[bin]]
name = "aleph"
path = "src/main.rs"
